// Automatically generated by make_root_pointers.py.

const char *readline_hist[(8)];
mp_obj_list_t mp_sys_argv_obj;
mp_obj_list_t mp_sys_path_obj;
mp_sched_item_t sched_queue[(1)];
vstr_t * repl_line;
